# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nearPDc <- function(X) {
    .Call(`_TrainSel_nearPDc`, X)
}

TrainSelC <- function(Data, CANDIDATES, setsizes, settypes, Stat, CD, Target, control, ntotal) {
    .Call(`_TrainSel_TrainSelC`, Data, CANDIDATES, setsizes, settypes, Stat, CD, Target, control, ntotal)
}

TrainSelCMOO <- function(Data, CANDIDATES, setsizes, settypes, Stat, nstat, control) {
    .Call(`_TrainSel_TrainSelCMOO`, Data, CANDIDATES, setsizes, settypes, Stat, nstat, control)
}

Kmatfunc <- function(Markers) {
    .Call(`_TrainSel_Kmatfunc`, Markers)
}

calculatecrossvalueM1 <- function(parent1, parent2, markereffects) {
    .Call(`_TrainSel_calculatecrossvalueM1`, parent1, parent2, markereffects)
}

calculatecrossvalueM2 <- function(Parents1, Parents2, markereffects, markermap, type = 0L, generation = 1L) {
    .Call(`_TrainSel_calculatecrossvalueM2`, Parents1, Parents2, markereffects, markermap, type, generation)
}

